baseurl = "https://blog.chann.kr/"
languageCode = "ko-kr"
title = "External Memory Storage"
theme = "hugo-material-blog"
metaDataFormat = "toml"
canonifyurls = true
googleAnalytics = "UA-65628430-3"
disqusShortname = "channprj"


# Custom Option
publishDir = "docs"
enableRobotsTXT = true
paginate = 5
PaginatePath = "page"


[params]
    # General information
    author = "CHANN"
    description = "Junior Developer"
    copyright = "CHANN"

    # Repository
    # provider = "GitHub"
    # repo_url = "https://github.com/channprj/blog"

    version = "1.0.0"
    logo = "img/profile.jpg"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "indigo"
        accent  = "deep-purple"

    [params.font]
        text = "Roboto"
        code = "Roboto Mono"


[social]
    twitter = "channprj"
    facebook = "channprj"
    linkedin = "channprj"
    behance = "channprj"
    github  = "channprj"
    # email   = "chann@chann.kr"


[[menu.main]]
    name   = "Home"
    url    = "/"
    weight = -10

[[menu.main]]
    name   = "About"
    url    = "about/"
    weight = 10

[[menu.main]]
    name   = "Posts"
    url    = "post/"
    weight = 20

[[menu.main]]
    name   = "Projects"
    url    = "projects/"
    weight = 30

# [[menu.main]]
#     name   = "License"
#     url    = "license/"
#     weight = 40


[blackfriday]
    smartypants	= true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
