baseurl = "https://blog.chann.kr/"
languageCode = "ko-kr"
author = "CHANN"
title = "External Memory Storage"
theme = "cocoa-eh"
footnoteReturnLinkContents = "↩"
metaDataFormat = "toml"
canonifyurls = true
googleAnalytics = "UA-65628430-3"
disqusShortname = "channprj"
publishdir = "docs"
layoutdir = "layouts"
contentdir = "content"
best = true

[permalinks]
blog = "blog/:slug/"

[params]
# General information
description = "Junior Developer"
copyright = "© CHANN"
dateform = "2006-01-31"
dateformfull = "2006-03-31 15:04:05 KST"
share = true
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "ko"
github = "channprj"
email = "chann@chann.kr"
linkedin = "channprj"
twitter = "channprj"
# social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = true

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true
hrefTargetBlank = true
